version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - ${WEB_PORT}:80
    env_file: .env
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'localhost:${WEB_PORT}');
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

  composer:
    restart: 'no'
    image: composer/composer:latest
    command: install
    volumes:
      - ./wordpress:/app

  wp-install:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    env_file: .env
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'localhost:${WEB_PORT}');
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
    command: >
      /bin/bash -c '
      sleep 10;
      wp core multisite-install --path="/var/www/html" --url="localhost:${WEB_PORT}" --title="CDS Wordpress Base" --admin_user=${ADMIN_USER} --admin_password=${ADMIN_PASSWORD} --admin_email=${ADMIN_EMAIL};
      wp theme enable cds-default --activate;
      wp plugin activate cds-base --network;
      wp plugin activate oasis-workflow --network;
      '
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
    networks:
      - app-network

  cli:
    container_name: cli
    depends_on:
      - db
      - wordpress
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'localhost:${WEB_PORT}');
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./:/home/default/project
    restart: unless-stopped
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge