version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .wp-env
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21.1-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - wordpress:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

  composer:
    restart: 'no'
    image: composer/composer:latest
    command: install
    volumes:
      - ./wordpress:/app

  wp-install:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    env_file: .wp-env
    command: >
      /bin/bash -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="localhost:8000" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=secret --admin_email=foo@bar.com;
      '
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  cli:
    container_name: cli
    depends_on:
      - db
      - wordpress
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/home/default/project
    restart: unless-stopped
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge