#!/bin/bash

die () {
    echo >&2 "$@"
    exit
}

# Load env vars
if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
else
  die "Missing .env"
fi

# Make sure .pem file exists
if [ ! -f $PEMFILE ]; then
  die ".pem key file missing"
fi

# More required config
if [ ! $SERVER_URL ] || [ ! $SERVER_PATH ]; then
  die "missing SERVER_URL or SERVER_PATH"
fi