#!/bin/bash

die () {
    echo >&2 "$@"
    exit
}

if [ -f $PATH_TO_SCRIPT/.env ]
then
  export $(cat $PATH_TO_SCRIPT/.env | sed 's/#.*//g' | xargs)
else
  die "Missing .env"
fi

if [ ! -f $PATH_TO_SCRIPT/$PEMFILE ] || [ ! $PATH_TO_SCRIPT/$PEMFILE ]; then
  die ".pem key file missing"
fi

if [ ! $SERVER_URL ] || [ ! $SERVER_PATH ]; then
  die "missing SERVER_URL or SERVER_PATH"
fi