service: aws-node-express-api

frameworkVersion: '2'

plugins:
  - serverless-aws-static-file-handler
  - serverless-offline

custom:
  apiGateway:
    binaryMediaTypes:
      - "*/*"


provider:
  name: aws
  runtime: nodejs12.x
  region: ca-central-1
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  static:
    handler: handler.static
    events:
      - http:
          path: /static/{proxy+}
          method: get

  favicon:
    handler: handler.favicon
    events:
      - http:
          path: /favicon.ico
          method: get

