version: '3'
services:
  wordpress:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../wordpress/wp-content:/var/www/html/wp-content
      - ../wordpress/.htaccess:/var/www/html/.htaccess
      - ../wordpress/wp-config.php:/var/www/html/wp-config.php
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: p4ssw0rd!
      AUTH_KEY: 5e78a80f581b3a2c008f37280112a866bd94697d
      SECURE_AUTH_KEY: 2b0dcc0b986ccf34cf0e2841bc8d519c2bff2bb6
      LOGGED_IN_KEY: 958c57a21bd9b8edacaabea2c6c5271acd1fd9fd
      NONCE_KEY: ebde6d6667f7a42be0be0f90f4ca53f68014c810
      AUTH_SALT: 5a5675018aab0948ba119f285c960588fe353fff
      SECURE_AUTH_SALT: cbeb9d93644aed795c7e8d13fa80dc24a19b9624
      LOGGED_IN_SALT: f227c720e51beca1488200aaee4ee3193823047b
      NONCE_SALT: ca865f80e1f3f58f48c97091fbd4ccf9bf293a59
    ports:
      - 80:80
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
networks:
  back:
volumes:
  db_data: