name: CI
on: [push, pull_request]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    name: PHP Pest tests
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: shivammathur/setup-php@v1
      with:
        php-version: 8.0
    - run: cd wordpress && composer install --prefer-dist --no-progress --no-suggest
    - run: cd wordpress && ./vendor/bin/pest
        