name: Deploy main branch

on:
  push:
    branches:
      - main
    paths:
      - "cds-snc-docs/**"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
       pwd
       cd cds-snc-docs
       pwd
       npm ci
       npm run build
       ls
       mkdir ../server/build
       cp -r ./build/* ../server/build
       cd ../server
       pwd
       ls

    
    
    
    #- name: serverless deploy
    #- run: cd server
      #uses: serverless/github-action@master
      #with:
        #args: deploy
      #env:
        #AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        #AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}