name: "Terraform security scan"

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/terraform-security-scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@6693d5f2dc45ab72428fcdb20e38b7fd14c8df50 #master as of Jun 10
        with:
          directory: terragrunt
          framework: terraform
