
name: "Terragrunt apply DEV"

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/terragrunt/**"
      - ".github/workflows/terragrunt-apply-dev.yml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.0.2
  TERRAGRUNT_VERSION: 0.31.0
  TF_VAR_cloudfront_custom_header_name: ${{ secrets.DEV_CLOUDFRONT_CUSTOM_HEADER_NAME }}
  TF_VAR_cloudfront_custom_header_value: ${{ secrets.DEV_CLOUDFRONT_CUSTOM_HEADER_VALUE }}

jobs:
  terragrunt-apply-dev:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/terragrunt
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Terragrunt apply DEV
        run: |
          cd infrastructure/terragrunt/env/dev
          terragrunt run-all apply --terragrunt-non-interactive